### ISSUE TITLE
root level container directory

### ISSUE THREAD

**Issue by matthiaaas** [ksv-vc/postbote#16]
Since some non-monorepo codebases might already use directory names such as `/previews` for other content than email templates, I'd suggest a single directory at root level to wrap all config subfolders like e.g Prisma already does.

```
├── postbote
    ├── emails
    └── previews
└── package.json
```

Not sure if a config file makes sense here (#11) or if this should be a endorsed default.

**Comment by iDuuck** [comment]
when the configuration you linked will be available (#11), there will be no default folder glob, but instead, this is a mandatory configuration you need to specify.
